default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password:
  port: 5432
  host: leave_postgres

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: leave_management_test
  username: postgres
  password: postgres
  port: 5432
  pool: 5
  host: localhost
  timeout: 5000